---
abstract: 'access the Magellan GPS Companion waypoints file'
author:
  - 'brian d foy <bdfoy@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Palm-Magellan-NavCompanion
no_index:
  directory:
    - t
    - inc
requires:
  Palm::Raw: '0'
  Palm::StdAppInfo: '0'
  Test::More: '0'
resources:
  repository: https://github.com/CPAN-Adopt-Me/Palm-Magellan-NavCompanion
version: '0.54'
